version: '3.8'

services:
  txtify:
    build:
      context: .
      dockerfile: Dockerfile
    image: lkmeta/txtify:latest
    container_name: txtify_container
    ports:
      - "8010:8010"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    restart: unless-stopped
