name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # Check out the code from the repository
    - uses: actions/checkout@v4

    # Build the Docker image
    - name: Build the Docker image
      run: docker build -t txtify-app:latest .
